### ISSUE TITLE
consider a super-basic documentation link for n00bs

### ISSUE THREAD

**Issue by staygroovy57** [TealNerd/AutoJoin#1]
I would say it's totally appropriate to include some short info in the readme.txt file, such as depencies, requirements and what to do; something as simple as: "download this and drop it into your ./minecraft/mods folder"

Alternately perhaps you may want to consider pointing them to Dr_Jawa's guide to installing mods, and as well request that on his side Dr_Jawa updates his mod guide to list your recent coding efforts (so you are mentioned on there)?

As if it needed to be repeated, thanks for making this available to the rest of us!

**Comment by TealNerd** [comment]
Yeah there's not much documentation to be had, but it should probably be added to the mod list
